# Generated by Django 4.2 on 2023-07-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_task_chek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='chek',
        ),
    ]
