# Generated by Django 4.2 on 2023-07-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_remove_task_chek'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
