# Generated by Django 4.2 on 2023-07-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(default='img.png', upload_to='image'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
