# Generated by Django 4.2 on 2023-07-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0009_task_img_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
