# Generated by Django 4.2 on 2023-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0010_alter_task_options_alter_task_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, default='img.png', upload_to='image'),
        ),
    ]
